mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='welcome_page'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('register_to_db', views.add_user_db, name='register_to_db'),
    path('', include('django.contrib.auth.urls')),
    path('homepage', views.my_view, name='myview'),
    path('manage_balance', views.income, name='income'),
    path('tweakbalance', views.tweakbalance, name='tweakbalance'),
    path('history_log', views.log_basic, name="history_log"),
    path('history_log/past_trans', views.past_trans, name="past_trans"),
    path('history_log/iograph', views.iograph, name="iograph"),
    path('history_log/balancegraph', views.balancegraph, name="balancegraph"),
    path('trans_chart_json', views.TransactionsView.as_view(), name="trans_chart_json"),
    path('balance_chart_json', views.BalanceView.as_view(), name="balance_chart_json"),
]

polls/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models

class Balance(models.Model):
	""" Balance range: -MAX_INTEGER < balance < MAX_INTEGER"""
	balance = models.IntegerField(default=0)
	owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=False)

	def __str__(self):
		return str(self.balance)

class Category(models.Model):
	text = models.CharField(max_length=20)
	def __str__(self):
		return self.text

class Log(models.Model):
	history_name = models.CharField(max_length=50, default="Default Log Name")
	date = models.DateTimeField(default=datetime.now, blank=True)
	category = models.CharField(max_length=20, default="Others")
	income_or_outcome = models.CharField(max_length=8, default="Income")
	owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=False)
	amount = models.IntegerField(default=1)
	balance = models.IntegerField(default=0)
	def __str__(self):
		return self.history_name

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import time
import sys
from random import randint
from django.views.generic import TemplateView
from chartjs.views.lines import BaseLineChartView
from .models import *


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'introduction_page'

	def get_queryset(self):
		"""Return the last five published questions."""
		pass

class RegisterView(generic.ListView):
	model = User
	template_name = 'polls/register.html'


def add_user_db(request):
	try:
		if User.objects.filter(username=request.POST['username']).exists():
			return render(request, 'polls/register.html', {
			'error_message': "Name taken!",
			})
			user.delete()
		elif User.objects.filter(email=request.POST['email']).exists():
			return render(request, 'polls/register.html', {
			'error_message': "Email taken!",
			})
			user.delete()
		else:
			user = User.objects.create_user(request.POST['username'], request.POST['email'],
			request.POST['password'])
			user.first_name = request.POST['first_name']
			user.last_name = request.POST['last_name']

	except(KeyError, Choice.DoesNotExist):
		return render(request, 'polls/register.html', {
			'error_message': "You didn't fill the form correctly.",
			})
		user.delete()
	else:
		user.save()
		user.balance_set.create()
		user.save()
		return HttpResponseRedirect(reverse('polls:login'))

@login_required
def my_view(request):
	myuser = request.user
	myuser_balance = Balance.objects.filter(owner=myuser)
	preview_balance = str(myuser_balance.get()) + "₪"
	preview_name = myuser.first_name + " " + myuser.last_name
	preview_email = myuser.email
	return render(request, 'polls/myview.html', {
		'name': preview_name,
		'balance': preview_balance,
		'email': preview_email,
		})

@login_required
def income(request):
	return render(request, 'polls/income.html', {
		'income_types': Category.objects.all()
		})

@login_required
def log_basic(request):
	myuser = request.user
	myuser_logs = Log.objects.filter(owner=myuser)
	return render(request, 'polls/log_basic.html', {
		'logs': myuser_logs
		})

@login_required
def past_trans(request):
	myuser = request.user
	myuser_logs = Log.objects.filter(owner=myuser)
	return render(request, 'polls/past_trans.html', {
		'logs': myuser_logs
		})

@login_required
def iograph(request):
	myuser = request.user
	myuser_logs = Log.objects.filter(owner=myuser)
	return render(request, 'polls/iograph.html', {
		'logs': myuser_logs
		})

@login_required
def balancegraph(request):
	myuser = request.user
	myuser_logs = Log.objects.filter(owner=myuser)
	return render(request, 'polls/balancegraph.html', {
		'logs': myuser_logs
		})

@login_required
def tweakbalance(request):
	amount = int(request.POST['amount'])
	type_of_trans="Income"
	if(request.POST['signofmoney'] == 'outcome'):
			amount *= -1
			type_of_trans="Outcome"
	myuser = request.user
	myuser_balance = Balance.objects.filter(owner=myuser).get()
	myuser_balance.balance = int(myuser_balance.balance) + int(amount)
	myuser_balance.save()
	myuser.save()
	history_name = time.strftime("%x") + " " + type_of_trans + ", " + request.POST['category']
	"""Add transaction to history log"""
	myuser.log_set.create(balance = myuser_balance.balance, history_name=history_name, category=request.POST['category'], income_or_outcome=type_of_trans, amount=amount)
	return HttpResponseRedirect(reverse('polls:income'), {'success': True})

@login_required
def history_log(request):
	myuser = request.user
	myuser_logs = Log.objects.filter(owner=myuser)
	return render(request, 'polls/logs.html', {
		'logs': myuser_logs
		})

class TransactionsView(BaseLineChartView):
	def get_labels(self):
		"""Return 7 labels for the x-axis."""
		myuser = self.request.user
		myuser_logs = Log.objects.filter(owner=myuser)
		income = [log.amount for log in myuser_logs if log.income_or_outcome == 'Income']
		outcome = [-1 * log.amount for log in myuser_logs if log.income_or_outcome == 'Outcome']
		
		transactions = max(len(income), len(outcome)) 
		return [i for i in range(1, transactions+1)]

	def get_providers(self):
		"""Return names of datasets."""
		return ["Income", "Expenses"]

	def get_data(self):
		"""Return 3 datasets to plot."""
		myuser = self.request.user
		myuser_logs = Log.objects.filter(owner=myuser)
		income = [log.amount for log in myuser_logs if log.income_or_outcome == 'Income']
		outcome = [-1 * log.amount for log in myuser_logs if log.income_or_outcome == 'Outcome']
		
		return [income,
				outcome]

class BalanceView(BaseLineChartView):
	def get_labels(self):
		"""Return 7 labels for the x-axis."""
		myuser = self.request.user
		myuser_logs = Log.objects.filter(owner=myuser)
		income = [log.amount for log in myuser_logs if log.income_or_outcome == 'Income']
		outcome = [-1 * log.amount for log in myuser_logs if log.income_or_outcome == 'Outcome']
		
		transactions = len(income)+  len(outcome) 
		return [i for i in range(1, transactions+1)]

	def get_providers(self):
		"""Return names of datasets."""
		return ["Balance"]

	def get_data(self):
		"""Return 3 datasets to plot."""
		myuser = self.request.user
		myuser_logs = Log.objects.filter(owner=myuser)
		balance = [log.balance for log in myuser_logs]
		
		return [balance]

polls/templates/accounts/register.html
<h1>Registeration Page</h1>

<form action="{%url 'polls:register_to_db' %}" method="post">
{% csrf_token %}
key key key
    Username: <input type="text" name="username" /><br/>
    Email: <input type="text" name="email" /><br/>
    Password: <input type="password" name="password" /><br/>
    First Name: <input type="text" name="first_name" /><br/>
    Last Name: <input type="text" name="last_name" /><br />
<input type="submit" value="Submit" />
</form>

polls/templates/base_generic.html
{% load staticfiles %}
<!DOCTYPE html lang="en">
<html>
	<head>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<link rel="icon" href="{% static 'img/ico.png' %}" />
    	{% block title %}
    	{% endblock %}
    	<meta name="description" content="">
    	<meta name="author" content="">
		<link rel="stylesheet" href="{% static 'css/sidemenu.css' %}" />

	</head>
<body>
	<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#"><img class="navbar-brand" src="{% static 'img/ico.png' %}" alt="" width="30" height="40">Money Management</a>

	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:welcome_page' %}">Homepage</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:welcome_page' %}">Homepage</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>

	</div>
    </nav>

    <div class="container-fluid">
    {% if user.is_authenticated %}
      <div class="row">
        {% block active %}

        {% endblock %}
     {% endif %}



        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
			{% block content %}

			{% endblock %}
        </main>
      </div>
    </div>
</body>
</html>

polls/templates/polls/balancegraph.html
{% extends "polls/logs.html" %}
{% load staticfiles %}
{% block log %}
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'polls:past_trans' %}">Past Transactions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'polls:iograph' %}">Income / Outcome Graph</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'polls:balancegraph' %}">Balance Overtime Graph</a>
            </li>
          </ul>
          <h1></h1>
<h2>A graph describing your balance over time:</h2><br />
<div class="col-md-offset-4 ">
		<canvas class="chart" id="myChart" ></canvas>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            $.get('{% url "polls:balance_chart_json" %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx, {
                    type: 'line', data: data
                });
            });
        </script>
</div>
{% endblock %}

polls/templates/polls/income.html
{% extends "base_generic.html" %}
{% load staticfiles %}
{% block content %}
<style>
    body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
    }
</style>
<h1>Manage your balance</h1>
{% if error_message %}
<h3> {{ error_message }} </h3>
{% endif %}
{% if success %}
<h3>Money added</h3>
{% endif %}
<form class="form-signin" action="{%url 'polls:tweakbalance' %}" method="post">
{% csrf_token %}
	<label for="id_amnt" class="sr-only">Amount</label>
	<input type="number" name="amount" id="id_amnt" maxlength="254" class="form-control" placeholder="Amount" required autofocus>
    <select class="form-control custom-select mb-2 mr-sm-2 mb-sm-0" name="category">
    {% for option in income_types %}
    	<option id="choice{{forloop.counter}}" value="{{option.text}}">{{ option.text }}</option>
    {% endfor %}
	</select>

    <select class="form-control custom-select mb-2 mr-sm-2 mb-sm-0" name="signofmoney">
    	<option value="income">Income</option>
    	<option value="outcome">Outcome</option>
	</select><br /> <br />
	<button class="btn btn-lg btn-primary btn-block" name="addmoney" value ="Update Balance" type="submit">Update Balance</button>
</form>
{% endblock %}

{% block active %}
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:myview' %}">Overview <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'polls:income' %}">Manage balance</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:history_log' %}">Logs</a>
            </li>
          </ul>

</nav>
{% endblock %}
{% block title %}
<title>Manage balance</title>
{% endblock %}

polls/templates/polls/index.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block content %}

Welcome to your bank account!

{% endblock %}

{% block active %}
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:myview' %}">Overview <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:income' %}">Manage balance</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:history_log' %}">Logs</a>
            </li>
          </ul>

        </nav>
{% endblock %}
{% block title %}
<title>Homepage</title>
{% endblock %}

polls/templates/polls/iograph.html
{% extends "polls/logs.html" %}
{% load staticfiles %}
{% block log %}
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'polls:past_trans' %}">Past Transactions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'polls:iograph' %}">Income / Outcome Graph</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:balancegraph' %}">Balance Overtime Graph</a>
            </li>
          </ul>
          <h1></h1>
<h2>A graph describing incomes and outcomes:</h2><br />
<div class="col-md-offset-4 ">
		<canvas class="chart" id="myChart" ></canvas>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            $.get('{% url "polls:trans_chart_json" %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx, {
                    type: 'line', data: data
                });
            });
        </script>
</div>
{% endblock %}

polls/templates/polls/line_chart.html
{% load staticfiles %}
<html>
    <head>
        <title>django-chartjs line chart demo</title>
        <!--[if lte IE 8]>
            <script src="{% static 'js/excanvas.js' %}"></script>
        <![endif]-->
    </head>
    <body>
        <h1>Some Line Charts loaded in Ajax!</h1>

        <canvas id="myChart" width="500" height="400"></canvas>

        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            $.get('{% url "polls:line_chart_json" %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx, {
                    type: 'line', data: data
                });
            });
        </script>
    </body>
</html>

polls/templates/polls/log_basic.html
{% extends "polls/logs.html" %}
{% load staticfiles %}
{% block log %}
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:past_trans' %}">Past Transactions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:iograph' %}">Income / Outcome Graph</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:balancegraph' %}">Balance Overtime Graph</a>
            </li>
          </ul>
          <h1></h1>
{% endblock %}

polls/templates/polls/logs.html
{% extends "base_generic.html" %}
{% load staticfiles %}
{% block content %}

<h1>{{ request.user.first_name }} {{ request.user.last_name }}'s Logs</h1><br />
{% block log %}

{% endblock %}

{% endblock %}

{% block active %}
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:myview' %}">Overview <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:income' %}">Manage balance</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'polls:history_log' %}">Logs</a>
            </li>
          </ul>
</nav>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}
{% block title %}
<title>History</title>
{% endblock %}

polls/templates/polls/myview.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block content %}


<h3>{{ name }}'s information</h3>

<strong style="color:grey">Your Balance:</strong> {{ balance }}<br />
<strong style="color:grey">Your Email:</strong> {{ email }}



{% endblock %}

{% block active %}
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'polls:myview' %}">Overview <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:income' %}">Manage balance</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:history_log' %}">Logs</a>
            </li>
          </ul>

</nav>
{% endblock %}
{% block title %}
<title>Dashboard</title>
{% endblock %}

polls/templates/polls/past_trans.html
{% extends "polls/logs.html" %}
{% load staticfiles %}
{% block log %}
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'polls:past_trans' %}">Past Transactions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:iograph' %}">Income / Outcome Graph</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:balancegraph' %}">Balance Overtime Graph</a>
            </li>
          </ul>
          <h1></h1>
<h2>A table of past transactions:</h2>
<table class="table">
	<thead>
	    <tr>
	        <th>Date</th>
	        <th>Category</th>
	        <th>Income / Outcome</th>
	        <th>Amount</th>
	    </tr>
	</thead>
	<tbody>
    {% for log in logs %}
	    <tr> 
	        <td>{{ log.date }} </td>
	        <td>{{ log.category }} </td>
	        <td>{{ log.income_or_outcome }} </td>
	        <td>{{ log.amount }} NIS</td>
	    </tr>
    {% endfor %}
	</tbody>
</table>
{% endblock %}

polls/templates/polls/register.html
{% load staticfiles %}
<!DOCTYPE html lang="en">
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
      }
      .form-signin .checkbox {
        font-weight: 400;
      }
      .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
      }
      .form-signin .form-control:focus {
        z-index: 2;
      }
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }
    </style>
    <title>Login</title>
    <link rel="icon" href="{% static 'img/ico.png' %}" />
  </head>
<body>
  <div class="container" style="">
    <div class="text-center">
      {% if error_message %}
<<<<<<< HEAD
      <p>{{ error_message }}</p>
=======
      <h1>{{ error_message }}</h1>
>>>>>>> d04df3141719a78674f468879bbfae9cfdda50bf
      {% endif %}

      {% if not user.is_authenticated  %}
      <form class="form-signin" method="post" action="{% url 'polls:register_to_db' %}">
      {% csrf_token %}
	      <img class="mb-4" src="{% static 'img/icon.jpg' %}" alt="" width="72" height="72">
	      <h1 class="h3 mb-3 font-weight-normal">Registeration page</h1>

	        <label for="id_username" class="sr-only">Username</label>
	        <input type="text" name="username" id="id_username" maxlength="254" class="form-control" placeholder="Username" required autofocus>

	        <label for="id_email" class="sr-only">Email</label>
	        <input type="email" name="email" id="id_email" class="form-control" placeholder="Email" required>

	        <label for="id_password" class="sr-only">Password</label>
	        <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>

	        <label for="id_fname" class="sr-only">First Name</label>
	        <input type="text" name="first_name" id="id_fname" class="form-control" placeholder="First Name" required>

	        <label for="id_lname" class="sr-only">Last Name</label>
	        <input type="text" name="last_name" id="id_lname" class="form-control" placeholder="Last Name" required><br />


	      <div>
	        <!-- <input type="submit" value="login" /> -->
	        <button class="btn btn-lg btn-primary btn-block"  value ="Register" type="submit">Register</button>
	        <input type="hidden" name="next" value="{{ next }}" />
	      </div>
      </form>
      {% endif %}

      <p><a href="{% url 'polls:login' %}">Do you have an account?</a></p>
      <p class="mt-5 mb-3 text-muted">&copy; 2018 Ofek Hayun's Money Management Website</p>
    </div>
  </div>
</body>
</html>

polls/templates/temp.html
	<!--
	<nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
          	<a href="{% url 'polls:welcome_page' %}"><img class="mb-4" src="{% static 'img/ico.png' %}" alt="" width="72" height="72"></a>
            <ul class="nav flex-column">
            	{% if user.is_authenticated %}
	              <li class="nav-item">
	                <a class="nav-link" href="{% url 'polls:myview' %}">
	                  <span data-feather="home"></span>
	                  Dashboard
	                </a>
	              </li>
	              <li class="nav-item">
	                <a class="nav-link" href="{% url 'polls:income' %}">
	                  <span data-feather="file"></span>
	                  Manage balance
	                </a>
	              </li>
	              <li class="nav-item">
	                <a class="nav-link" href="{% url 'polls:history_log' %}">
	                  <span data-feather="shopping-cart"></span>
	                  Transactions Log
	                </a>
	              </li>
	              <li class="nav-item">
	                <a class="nav-link" href="{% url 'polls:logout' %}">
	                  <span data-feather="users"></span>
	                  Logout
	                </a>
	              </li>
	            {% else %}
					<li class="nav-item">
		                <a class="nav-link" href="{% url 'polls:login' %}">
		                  <span data-feather="bar-chart-2"></span>
		                  Login
		                </a>
	              	</li>
	            {% endif %}
            </ul>
        <ul class="sidebar-nav">
		   {% if user.is_authenticated %}
		   	 <li><a href="{% url 'polls:myview' %}">Home</a></li>
		     <li>User: <strong style="color:#50c878">{{ user.get_username }}</strong></li>
		     <li><a href="{% url 'polls:income' %}">Manage balance</a></li>
		     <li><a href="{% url 'polls:history_log' %}">Transactions Log</a></li>
		     <li><a href="{% url 'polls:logout'%}">Logout</a></li>   
		   {% else%}
		     <li><a href="{% url 'polls:login'%}">Login</a></li>
		   {% endif %} 
		</ul>-->

<!--
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul> -->
          </div>
    </nav>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
		
		<div class="text-center" style="margin-right:130">
		{% block content %}

		{% endblock %}
		</div>
	</main> 